// Import the HashMap class
import java.util.HashMap;

public class HashmapConversion {
  public static void main(String[] args) {

    // Create a HashMap object 
    HashMap<String, Integer> Alphabet = new HashMap<String, Integer>();
    // Add keys and values (Letter, Value)
    Alphabet.put("A", 1);
    Alphabet.put("B", 2);
    Alphabet.put("C", 3);
	Alphabet.put("D", 4);
	Alphabet.put("E", 4);
	Alphabet.put("F", 5);
	Alphabet.put("G", 6);
	Alphabet.put("H", 8);
	Alphabet.put("I", 9);
	Alphabet.put("J", 10);
	Alphabet.put("K", 11);
	Alphabet.put("L", 12);
	Alphabet.put("M", 13);
	Alphabet.put("N", 14);
	Alphabet.put("O", 15);
	Alphabet.put("P", 16);
	Alphabet.put("Q", 17);
	Alphabet.put("R", 18);
	Alphabet.put("S", 19);
	Alphabet.put("T", 20);
	Alphabet.put("U", 21);
	Alphabet.put("V", 22);
	Alphabet.put("W", 23);
	Alphabet.put("X", 24);
	Alphabet.put("Y", 25);
	Alphabet.put("Z", 26);
    // (if needed) System.out.println(Alphabet); 
	
	HashMap<Integer, String> AlphabetInv = new HashMap<Integer, String>();
    AlphabetInv.put(1, "A");
    AlphabetInv.put(2, "B");
    AlphabetInv.put(3, "C");
	AlphabetInv.put(4, "D");
	AlphabetInv.put(5, "E");
	AlphabetInv.put(6, "F");
	AlphabetInv.put(7, "G");
	AlphabetInv.put(8, "H");
	AlphabetInv.put(9, "I");
	AlphabetInv.put(10, "J");,  
	AlphabetInv.put(11, "K");
	AlphabetInv.put(12, "L");
	AlphabetInv.put(13, "M");
	AlphabetInv.put(14, "N");
	AlphabetInv.put(15, "O");
	AlphabetInv.put(16, "P");
	AlphabetInv.put(17, "Q");
	AlphabetInv.put(18, "R");
	AlphabetInv.put(19, "S");
	AlphabetInv.put(20, "T");
	AlphabetInv.put(21, "U");
	AlphabetInv.put(22, "V");
	AlphabetInv.put(23, "W");
	AlphabetInv.put(24, "X");
	AlphabetInv.put(25, "Y");
	AlphabetInv.put(26, "Z");
	
	HashMap<String, Integer> Rotor1 = new HashMap<String, Integer>();
    Alphabet.put("A", 5);
    Alphabet.put("B", 11);
    Alphabet.put("C", 13);
	Alphabet.put("D", 6);
	Alphabet.put("E", 12);
	Alphabet.put("F", 7);
	Alphabet.put("G", 4);
	Alphabet.put("H", 17);
	Alphabet.put("I", 22);
	Alphabet.put("J", 26);
	Alphabet.put("K", 14);
	Alphabet.put("L", 20);
	Alphabet.put("M", 15);
	Alphabet.put("N", 23);
	Alphabet.put("O", 25);
	Alphabet.put("P", 8);
	Alphabet.put("Q", 24);
	Alphabet.put("R", 21);
	Alphabet.put("S", 19);
	Alphabet.put("T", 16);
	Alphabet.put("U", 1);
	Alphabet.put("V", 9);
	Alphabet.put("W", 2);
	Alphabet.put("X", 18);
	Alphabet.put("Y", 3);
	Alphabet.put("Z", 10);
	
	HashMap<String, Integer> Rotor2 = new HashMap<String, Integer>();
    Alphabet.put("A", 1);
    Alphabet.put("B", 10);
    Alphabet.put("C", 4);
	Alphabet.put("D", 11);
	Alphabet.put("E", 19);
	Alphabet.put("F", 9);
	Alphabet.put("G", 18);
	Alphabet.put("H", 21);
	Alphabet.put("I", 24);
	Alphabet.put("J", 2);
	Alphabet.put("K", 12);
	Alphabet.put("L", 8);
	Alphabet.put("M", 23);
	Alphabet.put("N", 20);
	Alphabet.put("O", 13);
	Alphabet.put("P", 3);
	Alphabet.put("Q", 17);
	Alphabet.put("R", 7);
	Alphabet.put("S", 26);
	Alphabet.put("T", 14);
	Alphabet.put("U", 16);
	Alphabet.put("V", 25);
	Alphabet.put("W", 6);
	Alphabet.put("X", 22);
	Alphabet.put("Y", 15);
	Alphabet.put("Z", 5);
	
	HashMap<String, Integer> Rotor3 = new HashMap<String, Integer>();
    Alphabet.put("A", 2);
    Alphabet.put("B", 4);
    Alphabet.put("C", 6);
	Alphabet.put("D", 8);
	Alphabet.put("E", 10);
	Alphabet.put("F", 12);
	Alphabet.put("G", 3);
	Alphabet.put("H", 16);
	Alphabet.put("I", 18);
	Alphabet.put("J", 20);
	Alphabet.put("K", 24);
	Alphabet.put("L", 22);
	Alphabet.put("M", 26);
	Alphabet.put("N", 14);
	Alphabet.put("O", 25);
	Alphabet.put("P", 5);
	Alphabet.put("Q", 9);
	Alphabet.put("R", 23);
	Alphabet.put("S", 7);
	Alphabet.put("T", 1);
	Alphabet.put("U", 11);
	Alphabet.put("V", 13);
	Alphabet.put("W", 21);
	Alphabet.put("X", 19);
	Alphabet.put("Y", 17);
	Alphabet.put("Z", 15);
	
	HashMap<String, Integer> Rotor4 = new HashMap<String, Integer>();
    Alphabet.put("A", 5);
    Alphabet.put("B", 19);
    Alphabet.put("C", 15);
	Alphabet.put("D", 22);
	Alphabet.put("E", 16);
	Alphabet.put("F", 26);
	Alphabet.put("G", 10);
	Alphabet.put("H", 1);
	Alphabet.put("I", 25);
	Alphabet.put("J", 17);
	Alphabet.put("K", 21);
	Alphabet.put("L", 9);
	Alphabet.put("M", 18);
	Alphabet.put("N", 8);
	Alphabet.put("O", 24);
	Alphabet.put("P", 12);
	Alphabet.put("Q", 14);
	Alphabet.put("R", 6);
	Alphabet.put("S", 20);
	Alphabet.put("T", 7);
	Alphabet.put("U", 11);
	Alphabet.put("V", 4);
	Alphabet.put("W", 3);
	Alphabet.put("X", 13);
	Alphabet.put("Y", 23);
	Alphabet.put("Z", 2);

	HashMap<String, Integer> Rotor5 = new HashMap<String, Integer>();
    Alphabet.put("A", 22);
    Alphabet.put("B", 26);
    Alphabet.put("C", 2);
	Alphabet.put("D", 18);
	Alphabet.put("E", 7);
	Alphabet.put("F", 9);
	Alphabet.put("G", 20);
	Alphabet.put("H", 25);
	Alphabet.put("I", 21);
	Alphabet.put("J", 16);
	Alphabet.put("K", 19);
	Alphabet.put("L", 4);
	Alphabet.put("M", 14);
	Alphabet.put("N", 8);
	Alphabet.put("O", 12);
	Alphabet.put("P", 24);
	Alphabet.put("Q", 1);
	Alphabet.put("R", 23);
	Alphabet.put("S", 13);
	Alphabet.put("T", 10);
	Alphabet.put("U", 17);
	Alphabet.put("V", 15);
	Alphabet.put("W", 6);
	Alphabet.put("X", 5);
	Alphabet.put("Y", 3);
	Alphabet.put("Z", 11);
	  
	  HashMap<String, Integer> ReflectorUKWC = new HashMap<String, Integer>();
    Alphabet.put("A", 6);
    Alphabet.put("B", 22);
    Alphabet.put("C", 16);
	Alphabet.put("D", 10);
	Alphabet.put("E", 9);
	Alphabet.put("F", 1);
	Alphabet.put("G", 15);
	Alphabet.put("H", 25);
	Alphabet.put("I", 5);
	Alphabet.put("J", 4);
	Alphabet.put("K", 18);
	Alphabet.put("L", 26);
	Alphabet.put("M", 24);
	Alphabet.put("N", 23);
	Alphabet.put("O", 7);
	Alphabet.put("P", 3);
	Alphabet.put("Q", 20);
	Alphabet.put("R", 11);
	Alphabet.put("S", 21);
	Alphabet.put("T", 17);
	Alphabet.put("U", 19);
	Alphabet.put("V", 2);
	Alphabet.put("W", 14);
	Alphabet.put("X", 13);
	Alphabet.put("Y", 8);
	Alphabet.put("Z", 12);
	
  }
}

// https://www.w3schools.com/java/java_hashmap.asp
//capitalCities.get(" imput ") to get the value 
